### ISSUE TITLE
Version dependencies

### ISSUE THREAD

**Issue by KevinEsh** [paulkastel/JobShopPRO#3]
Hello, I'm very interested in your project. Which version of ortools did you use to build your code? Is there any Pipfile to make installation more easy?

**Comment by paulkastel** [comment]
@KevinEsh Hey, sorry but there is no pipfile to make installation easier, follow the commands from readme, and as I remember i used version v7.4 of ortools

**Comment by KevinEsh** [comment]
Thanks man. I could install your project. Really really great.
